const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})


const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate's profile matches the job describe"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question can be asked in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Technical questions that can be asked in the interview along with their intention and how to answer them"),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The technical question can be asked in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Behavioral questions that can be asked in the interview along with their intention and how to answer them"),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill which the candidate is lacking"),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of this skill gap, i.e. how important is this skill for the job and how much it can impact the candidate's chances")
    })).describe("List of skill gaps in the candidate's profile along with their severity"),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day number in the preparation plan, starting from 1"),
        focus: z.string().describe("The main focus of this day in the preparation plan, e.g. data structures, system design, mock interviews etc."),
        tasks: z.array(z.string()).describe("List of tasks to be done on this day to follow the preparation plan, e.g. read a specific book or article, solve a set of problems, watch a video etc.")
    })).describe("A day-wise preparation plan for the candidate to follow in order to prepare for the interview effectively"),
    title: z.string().describe("The title of the job for which the interview report is generated"),
})


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
    const prompt = `Generate an interview report for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}`

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: z.toJSONSchema(interviewReportSchema),
        }
    })

    return JSON.parse(response.text)
}


async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: z.toJSONSchema(resumePdfSchema),
        }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}


/**
 * Generate interview questions based on resume and job role
 */
async function generateMockInterviewQuestions({ resume, jobRole, jobDescription, questionCount }) {
    const mockQuestionsSchema = z.object({
        questions: z.array(z.object({
            question: z.string().describe("The interview question to ask the candidate"),
            category: z.enum(["technical", "behavioral", "project"]).describe("The category of the question")
        }))
    });

    const prompt = `You are conducting a mock interview for a ${jobRole} position.
                    
                    Candidate's Resume: ${resume}
                    ${jobDescription ? `Job Description: ${jobDescription}` : ''}
                    
                    Generate exactly ${questionCount} interview questions that:
                    1. Are specific to the candidate's resume and projects
                    2. Mix technical, behavioral, and project-based questions
                    3. Progress from easier to harder
                    4. Test both technical knowledge and communication skills
                    
                    Question distribution:
                    - ${Math.floor(questionCount * 0.5)} technical questions (about skills, technologies, concepts)
                    - ${Math.floor(questionCount * 0.3)} project-based questions (about specific projects in resume)
                    - ${Math.ceil(questionCount * 0.2)} behavioral questions (problem-solving, teamwork, challenges)
                    
                    Make questions conversational and realistic, like a real interviewer would ask.`;

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: z.toJSONSchema(mockQuestionsSchema),
        }
    });

    const result = JSON.parse(response.text);
    return result.questions;
}



/**
 * Evaluate all answers at once after interview completion
 */
async function evaluateAllAnswers({ questions, answers, resume, jobRole }) {
    const evaluationSchema = z.object({
        evaluations: z.array(z.object({
            questionIndex: z.number().describe("The index of the question being evaluated"),
            scores: z.object({
                clarity: z.number().min(0).max(10).describe("How clear and articulate the answer was (0-10)"),
                technical: z.number().min(0).max(10).describe("Technical accuracy and depth of knowledge (0-10)"),
                confidence: z.number().min(0).max(10).describe("Confidence in delivery, minimal hesitation (0-10)"),
                completeness: z.number().min(0).max(10).describe("How thoroughly the question was answered (0-10)")
            }),
            feedback: z.string().describe("Brief constructive feedback on this specific answer (2-3 sentences)")
        }))
    });

    // Prepare questions and answers for AI or context for AI to evaluate
    const qaContext = answers.map((answer, index) => ({
        // questionIndex: answer.questionIndex,
        // question: questions[answer.questionIndex].questionText,
        // category: questions[answer.questionIndex].category,
        questionIndex: index, // NOT answer.questionIndex
        question: questions[index]?.questionText,
        category: questions[index]?.category,
        answer: answer.transcript,
        wordCount: answer.wordCount,
        fillerWordCount: answer.fillerWordCount,
        speakingPace: answer.speakingPace,
        duration: answer.duration
    }));

    const prompt = `You are evaluating a mock interview for a ${jobRole} position.
                    
                    Candidate's Resume: ${resume}
                    
                    Interview Q&A:
                    ${qaContext.map((qa, i) => `
                    Q${i + 1} (${qa.category}): ${qa.question}
                    Answer: ${qa.answer}
                    Stats: ${qa.wordCount} words, ${qa.fillerWordCount} filler words, ${qa.speakingPace} WPM, ${qa.duration}s duration
                    `).join('\n')}
                    
                    For each answer, provide:
                    1. Clarity score (0-10): Communication quality, articulation, flow
                    2. Technical score (0-10): Accuracy, depth, relevance
                    3. Confidence score (0-10): Assertiveness, minimal hesitation, strong delivery
                    4. Completeness score (0-10): Thoroughness, covered all aspects
                    5. Brief feedback: 2-3 sentences of constructive criticism
                    
                    Be fair but honest. Score based on the job role expectations.`;

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: z.toJSONSchema(evaluationSchema),
        }
    });

    const result = JSON.parse(response.text);

    // Merge evaluations back into answers
    // return answers.map((answer, index) => {
    //     const evaluation = result.evaluations.find(e => e.questionIndex === answer.questionIndex);
    //     return {
    //         ...answer,
    //         scores: evaluation.scores,
    //         aiFeedback: evaluation.feedback
    //     };
    // });
    return answers.map((answer, index) => {
    const evaluation = result.evaluations[index];

    return {
        ...answer,
        scores: evaluation?.scores || {
            clarity: 5,
            technical: 5,
            confidence: 5,
            completeness: 5
        },
        aiFeedback: evaluation?.feedback || "No feedback generated"
    };
});
}



/**
 * Generate overall strengths, improvements, and detailed feedback
 */
async function generateFinalFeedback({ jobRole, answers, questions, finalScore }) {
    const feedbackSchema = z.object({
        strengths: z.array(z.string()).describe("3-5 key strengths demonstrated in the interview"),
        improvements: z.array(z.string()).describe("3-5 specific areas for improvement"),
        detailedFeedback: z.string().describe("A comprehensive 3-4 paragraph feedback covering overall performance, communication style, technical knowledge, and actionable next steps")
    });

    // Prepare context
    // const performanceContext = answers.map((answer, index) => ({
    //     question: questions[answer.questionIndex].questionText,
    //     category: questions[answer.questionIndex].category,
    //     scores: answer.scores,
    //     feedback: answer.aiFeedback,
    //     fillerWordCount: answer.fillerWordCount,
    //     speakingPace: answer.speakingPace
    // }));
    const performanceContext = answers.map((answer, index) => {
    const question = questions[index]; // use index, not questionIndex

    return {
        question: question?.questionText || "Unknown question",
        category: question?.category || "unknown",
        scores: answer.scores,
        feedback: answer.aiFeedback,
        fillerWordCount: answer.fillerWordCount,
        speakingPace: answer.speakingPace
    };
});

    const prompt = `You are providing final feedback for a ${jobRole} mock interview.
                    
                    Final Scores:
                    - Overall: ${finalScore.overall}/100
                    - Communication: ${finalScore.communication}/100
                    - Technical: ${finalScore.technical}/100
                    - Confidence: ${finalScore.confidence}/100
                    
                    Performance per question:
                    ${performanceContext.map((p, i) => `
                    Q${i + 1} (${p.category}): ${p.question}
                    Scores: Clarity ${p.scores.clarity}/10, Technical ${p.scores.technical}/10, Confidence ${p.scores.confidence}/10, Complete ${p.scores.completeness}/10
                    Feedback: ${p.feedback}
                    `).join('\n')}
                    
                    Based on this interview performance, provide:
                    
                    1. STRENGTHS (3-5 points): What did they do well? Be specific.
                    2. IMPROVEMENTS (3-5 points): What needs work? Be actionable and constructive.
                    3. DETAILED FEEDBACK (3-4 paragraphs):
                       - Overall performance summary
                       - Communication style analysis
                       - Technical knowledge assessment
                       - Specific actionable advice for improvement
                    
                    Be encouraging but honest. Focus on helping them succeed in real interviews.`;

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: z.toJSONSchema(feedbackSchema),
        }
    });

    return JSON.parse(response.text);
}



module.exports = {
    generateInterviewReport,
    generateMockInterviewQuestions,
    evaluateAllAnswers,
    generateFinalFeedback,
    generateResumePdf
}